// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEPK0XtqkNhpMGu-UTh-qUyRXV3sky6Gs',
    appId: '1:587632560462:web:3dc9d17c23e061dcfff61f',
    messagingSenderId: '587632560462',
    projectId: 'auth-test-f3a44',
    authDomain: 'auth-test-f3a44.firebaseapp.com',
    storageBucket: 'auth-test-f3a44.appspot.com',
    measurementId: 'G-0RNGRR9S0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1XW_rp8K-e5clZUQML2KKGHvNlsJ02Oc',
    appId: '1:587632560462:android:3ef227a51fd30ecefff61f',
    messagingSenderId: '587632560462',
    projectId: 'auth-test-f3a44',
    storageBucket: 'auth-test-f3a44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB5r4RSo2oObQBKZvpD59DOCSyQHLKxWo',
    appId: '1:587632560462:ios:1f29244f54f18cb6fff61f',
    messagingSenderId: '587632560462',
    projectId: 'auth-test-f3a44',
    storageBucket: 'auth-test-f3a44.appspot.com',
    iosBundleId: 'com.example.anmeldung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB5r4RSo2oObQBKZvpD59DOCSyQHLKxWo',
    appId: '1:587632560462:ios:e96d584f03a6f3f9fff61f',
    messagingSenderId: '587632560462',
    projectId: 'auth-test-f3a44',
    storageBucket: 'auth-test-f3a44.appspot.com',
    iosBundleId: 'com.example.anmeldung.RunnerTests',
  );
}
